version: "0.2"
ignorePaths:
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
useGitignore: true
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - bash
  - cpp-compound-words
  - css
  - custom-dictionary
  - en-gb
  - npm
  - softwareTerms
words:
  - mirae
ignoreWords: []
