# Prettier friendly markdownlint config (all formatting rules disabled)
extends: markdownlint/style/prettier
# Bare URL used
MD034: false
# First line in a file should be a top-level heading
MD041: false
